config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :pages

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = related_pages
    @last_page = @pages.max_by do |page|
      page.updated_at
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    # @related_pages = Page.order('random').limit(3)
    @related_pages = related_pages
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:title, :content, :security)
    end

    def related_pages
      Page.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown_to_html(markdown)
    unless @markdown
      renderer = Redcarpet::Render::HTML.new
      @markdown = Redcarpet::Markdown.new(renderer)
    end
    @markdown.render(markdown).html_safe
  end
end

def markdown_to_text(markdown)
  Nokogiri::HTML(markdown_to_html(markdown)).text
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class = 'footer'>
  MECANIAN 2016
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mecanian</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class = 'main'>
    <span class = 'logo' >
      <%= link_to root_path do %>
        <%= image_tag asset_path "logo.png" %>
      <% end %>
    </span>
    <br>
    <%= yield %>
    <br>
    <div class = 'footer'>
      MECANIAN 2016
    </div>
  </div>
</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>
      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  Title:
  <%= f.text_field :title, :class => "form form-field" %>
  Content (Markdown compatible):
  <%= f.text_area :content, :class => "form form-area" %>
  <%= f.submit %>

<% end %>

app/views/pages/_navi.html.erb
<div class = 'navi'>
  <div class = 'leftbox'>
    <% if action_name == 'index' or action_name == 'show' %>
      <%= link_to 'ABOUT', root_path, :class => "badge static-badge" %>
      <%= link_to 'REQUEST', root_path, :class => "badge static-badge" %>
      <%= link_to 'LOGIN', root_path, :class => "badge static-badge" %>
    <% end %>
  </div>
  <div class = 'rightbox'>
    <% if action_name == 'show' %>
      <%= link_to 'Edit Page', edit_page_path(@page), :class => "badge responsive-badge" %>
    <% end %>

    <% if action_name == 'index' or action_name == 'show' %>
      <%= link_to 'New Page', new_page_path, :class => "badge responsive-badge" %>
    <% end %>
  </div>
</div>

app/views/pages/_page.html.erb
<span class = 'page'>
  <h1 class = 'title'><%= page.title %></h1>
  <p><%= page.updated_at %></p>
  <%= markdown_to_html(page.content) %> 
</span>

app/views/pages/_page_mini.html.erb
<%= link_to page do %>
  <div class = 'page-mini' >
    <h2><%= page.title %></h2>
    <%= page.updated_at %><br>
    <%= markdown_to_text page.content %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<%= render 'form' %>

app/views/pages/index.html.erb
<% if @last_page %>
  <i>Last Update: <%= @last_page.updated_at %></i>
<% end %>

<%= notice %>
<%= render partial: 'navi' %>
<% @pages.each do |page| %>
  <%= render partial: 'page_mini', locals: {page: page} %>
<% end %>

app/views/pages/new.html.erb
<h1>New Page</h1>
<%= render 'form' %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>
<%= render partial: 'navi' %>
<%= render partial: 'page', locals: {page: @page} %>
<% @related_pages.each do |page| %>
  <%= render partial: 'page_mini', locals: {page: page} %>
<% end %>